"""Chats

Revision ID: 79af1de7e242
Revises: a7b0c0ecc9b4
Create Date: 2025-05-03 23:24:35.573172

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79af1de7e242'
down_revision: Union[str, None] = 'a7b0c0ecc9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
                    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('therapist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('military_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('last_updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('last_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['military_id'], ['military.id'], ),
                    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chatmessages',
                    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('sent_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatmessages')
    op.drop_table('chats')
    # ### end Alembic commands ###
