"""initial

Revision ID: a738c4f98b9a
Revises: 
Create Date: 2025-04-12 22:55:30.210750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a738c4f98b9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertise',
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('CBT', 'HUMANISTIC', 'PTSD', 'EXISTENTIAL', 'GROUP', 'NEURO', 'CLINICAL', 'STRESS_ANXIETY', 'COUNSELING', 'GRIEF_LOSS', 'ADDICTION', 'CRISIS', name='therapistexpertiseenum'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('military',
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('MILITARY', 'THERAPIST', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapist',
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('MILITARY', 'THERAPIST', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_test_results',
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('military_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['military_id'], ['military.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'military_id')
    )
    op.create_table('militaryprofile',
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marriage_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'SEPARATED', 'WIDOWED', name='marriagestatus'), nullable=False),
    sa.Column('kids', sa.Integer(), nullable=False),
    sa.Column('hobbies', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('complains', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insecures', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anxieties', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['military.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('therapist_expertise',
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expertise_code', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_code'], ['expertise.code'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('expertise_code', 'therapist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapist_expertise')
    op.drop_table('militaryprofile')
    op.drop_table('assessment_test_results')
    op.drop_table('therapist')
    op.drop_table('military')
    op.drop_table('expertise')
    # ### end Alembic commands ###
